Strategies:
    Extended: "Wiechert\\DataTablesBundle\\TableGenerator\\EntityReflection\\Strategies\\ExtendedStrategy"
    Simple:   "Wiechert\\DataTablesBundle\\TableGenerator\\EntityReflection\\Strategies\\SimpleStrategy"
    Default: "Wiechert\\DataTablesBundle\\TableGenerator\\EntityReflection\\Strategies\\SimpleStrategy"
