Datatables:
  Bundles:
    WiechertDataTablesBundle:
      namespace: "Wiechert\\DataTablesBundle\\Entity\\"
      Tables:
        Category:
            display_name:         "All the categories"
            title:                "Category overview"
            Actions:
              PHPActions:
                - {name: "Display", route: "wiechert_core_generic_entity_display"}

        Product:
            display_name:         "All the categories"
            title:                "Category overview"
            Actions:
                PHPActions:
                   - {name: "Display", route: "wiechert_core_generic_entity_display"}

        Position:
                display_name:         "All the categories"
                title:                "Category overview"
                Actions:
                    PHPActions:
                       - {name: "Display", route: "wiechert_core_generic_entity_display"}

        Order:
                  display_name:         "All the order"
                  title:                "Order overview"
                  Actions:
                      PHPActions:
                         - {name: "Display", route: "wiechert_core_generic_entity_display"}

      NamedTables:
        Category:
             get_subcategories:
                  title:               "sub categories"
                  description:         "get all sub categories"
                  select_table:         "Category"
                  select_table_bundle:  "WiechertDataTablesBundle"
                  joins:
                      - ["e0.rootcategory", "f"]
                  where_caluse:         "f.id = :id"

             get_rootcategories:
                  title:               "root categories"
                  description:         "get all root categories"
                  select_table:         "Category"
                  select_table_bundle:  "WiechertDataTablesBundle"
                  joins:
                      - ["e0.subcategories", "f"]
                  where_caluse:         "f.id = :id"

             get_products:
                  title:              "every product of this category"
                  description:        "list all producs of this category"
                  select_table:         "Product"
                  select_table_bundle:  "WiechertDataTablesBundle"
                  joins:
                      - ["e0.categories", "f"]
                  where_caluse:         "f.id = :id"

        Order:
             get_positions:
                  title:               "Positions of the order"
                  description:         "get all positions"
                  select_table:         "Position"
                  select_table_bundle:  "WiechertDataTablesBundle"
                  joins:
                       - ["e0.order", "f"]
                  where_caluse:         "f.id = :id"

        Product:
             get_categories:
                  title:               "Categories of the product"
                  description:         "get all categories"
                  select_table:         "Category"
                  select_table_bundle:  "WiechertDataTablesBundle"
                  joins:
                       - ["e0.products", "f"]
                  where_caluse:         "f.id = :id"






